SHDjango/SHDjangolesson/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# from app01.views import hello_world
from statistic.views import render_index
import xadmin
from django.views.generic.base import RedirectView

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^app/', include('app01.urls')),
    url(r'^message/', include('message.urls')),
    url(r'^shtml/', include('statistic.urls')),
# url(r'^account/', include('account.urls', namespace='account', app_name='account')),
    url(r'^ueditor/',include('DjangoUeditor.urls')),
    url(r'^comments/', include("comments.urls")),
    url(r'^$',RedirectView.as_view(url='/app/index/')),
]

SHDjango/apps/app01/urls.py
from django.conf.urls import url
# from app01.views import ForCodeView
from app01.index_handler import indexHandLer
from app01.search_handler import SearchHandler
from app01.detail_handler import DetailHandler,ArtCapterHandler
from app01.user_manage import RegisterHandler,LoginHandler,LogoutHandler,create_code_img
from app01 import cart_handler

urlpatterns = [

    url(r'^index/$', indexHandLer),
    url(r'^search/$', SearchHandler),
    url(r'^detail/$', DetailHandler),
    url(r'^register/$', RegisterHandler,name='user_register'),
    url(r'^login/$', LoginHandler,name='user_login'),
    url(r'^logout/$', LogoutHandler,name='user_logout'),
    url(r'^cart/view/$', cart_handler.ViewCartHandler),
    url(r'^cart/add/$', cart_handler.AddCartHandler),
    url(r'^cart/clean/$', cart_handler.CleanCartHandler),
	url(r'^cart/order/$', cart_handler.CartOrderHandler),
    url(r'^capter/$', ArtCapterHandler),
    url(r'^create_code_img/$', create_code_img),
    url(r'^cart/submit_order/$',cart_handler.OrderSubmitHandler,name='product_order'),
    # url(r'^forcode/$', ForCodeView.as_view(),name='forcode'),

]

SHDjango/apps/comments/urls.py
from django.conf.urls import url
from comments import views
app_name = 'comments'

urlpatterns = [
    url(r'^app/(?P<art_pk>[0-9]+)/$', views.art_comment, name='art_comment'),


]

SHDjango/extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

SHDjango/apps/app01/views.py
'''
import re
import random

from django.http import HttpResponse
from django.views import View

from SHDjangolesson.settings import APIKEY
from .models import ArtsUser
from SHDjangolesson.note_check import YunPian




class ForCodeView(View):
    """获取手机验证码"""

    def post(self, request):
        mobile = request.POST.get('mobile', '')
        if mobile:
            # 验证是否为有效手机号
            mobile_pat = re.compile('^(13\d|14[5|7]|15\d|166|17\d|18\d)\d{8}$')
            res = re.search(mobile_pat, mobile)
            if res:
                # 生成手机验证码
                code = ArtsUser()
                code.mobile = mobile
                c = random.randint(1000, 9999)
                code.code = str(c)
                code.save()
                code = ArtsUser.objects.filter(mobile=mobile).first().code
                yunpian = YunPian(APIKEY)
                sms_status = yunpian.send_sms(code=code, mobile=mobile)
                msg = sms_status.msg
                return HttpResponse(msg)
            else:
                msg = '请输入有效手机号码!'
                return HttpResponse(msg)
        else:
            msg = '手机号不能为空！'
            return HttpResponse(msg)

'''

SHDjango/extra_apps/xadmin/views/detail.py
from __future__ import absolute_import
import copy

from crispy_forms.utils import TEMPLATE_PACK
from django import forms
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.db import models
from django.forms.models import modelform_factory
from django.http import Http404
from django.template import loader
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.encoding import force_text, smart_text
from django.utils.html import escape
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext as _
from django.utils.html import conditional_escape
from xadmin.layout import FormHelper, Layout, Fieldset, Container, Column, Field, Col, TabHolder
from xadmin.util import unquote, lookup_field, display_for_field, boolean_icon, label_for_field

from .base import ModelAdminView, filter_hook, csrf_protect_m

# Text to display within change-list table cells if the value is blank.
EMPTY_CHANGELIST_VALUE = _('Null')


class ShowField(Field):
    template = "xadmin/layout/field_value.html"

    def __init__(self, callback, *args, **kwargs):
        super(ShowField, self).__init__(*args, **kwargs)
        self.results = [(field, callback(field)) for field in self.fields]

    def render(self, form, form_style, context, template_pack=TEMPLATE_PACK, extra_context=None, **kwargs):
        super(ShowField, self).render(form, form_style, context, template_pack, extra_context, **kwargs)
        if extra_context is None:
            extra_context = {}
        if hasattr(self, 'wrapper_class'):
            extra_context['wrapper_class'] = self.wrapper_class

        if self.attrs:
            if 'detail-class' in self.attrs:
                extra_context['input_class'] = self.attrs['detail-class']
            elif 'class' in self.attrs:
                extra_context['input_class'] = self.attrs['class']

        html = ''
        for field, result in self.results:
            extra_context['result'] = result
            if field in form.fields:
                if form.fields[field].widget != forms.HiddenInput:
                    extra_context['field'] = form[field]
                    html += loader.render_to_string(self.template, extra_context)
            else:
                extra_context['field'] = field
                html += loader.render_to_string(self.template, extra_context)
        return html


class ResultField(object):

    def __init__(self, obj, field_name, admin_view=None):
        self.text = '&nbsp;'
        self.wraps = []
        self.allow_tags = False
        self.obj = obj
        self.admin_view = admin_view
        self.field_name = field_name
        self.field = None
        self.attr = None
        self.label = None
        self.value = None

        self.init()

    def init(self):
        self.label = label_for_field(self.field_name, self.obj.__class__,
                                     model_admin=self.admin_view,
                                     return_attr=False
                                     )
        try:
            f, attr, value = lookup_field(
                self.field_name, self.obj, self.admin_view)
        except (AttributeError, ObjectDoesNotExist):
            self.text
        else:
            if f is None:
                self.allow_tags = getattr(attr, 'allow_tags', False)
                boolean = getattr(attr, 'boolean', False)
                if boolean:
                    self.allow_tags = True
                    self.text = boolean_icon(value)
                else:
                    self.text = smart_text(value)
            else:
                if isinstance(f.rel, models.ManyToOneRel):
                    self.text = getattr(self.obj, f.name)
                else:
                    self.text = display_for_field(value, f)
            self.field = f
            self.attr = attr
            self.value = value

    @property
    def val(self):
        text = mark_safe(
            self.text) if self.allow_tags else conditional_escape(self.text)
        if force_text(text) == '' or text == 'None' or text == EMPTY_CHANGELIST_VALUE:
            text = mark_safe(
                '<span class="text-muted">%s</span>' % EMPTY_CHANGELIST_VALUE)
        for wrap in self.wraps:
            text = mark_safe(wrap % text)
        return text


def replace_field_to_value(layout, cb):
    cls_str = str if six.PY3 else basestring
    for i, lo in enumerate(layout.fields):
        if isinstance(lo, Field) or issubclass(lo.__class__, Field):
            layout.fields[i] = ShowField(
                cb, *lo.fields, attrs=lo.attrs, wrapper_class=lo.wrapper_class)
        elif isinstance(lo, cls_str):
            layout.fields[i] = ShowField(cb, lo)
        elif hasattr(lo, 'get_field_names'):
            replace_field_to_value(lo, cb)


class DetailAdminView(ModelAdminView):

    form = forms.ModelForm
    detail_layout = None
    detail_show_all = True
    detail_template = None
    form_layout = None

    def init_request(self, object_id, *args, **kwargs):
        self.obj = self.get_object(unquote(object_id))

        if not self.has_view_permission(self.obj):
            raise PermissionDenied

        if self.obj is None:
            raise Http404(
                _('%(name)s object with primary key %(key)r does not exist.') %
                {'name': force_text(self.opts.verbose_name), 'key': escape(object_id)})
        self.org_obj = self.obj

    @filter_hook
    def get_form_layout(self):
        layout = copy.deepcopy(self.detail_layout or self.form_layout)

        if layout is None:
            layout = Layout(Container(Col('full',
                                          Fieldset(
                                              "", *self.form_obj.fields.keys(),
                                              css_class="unsort no_title"), horizontal=True, span=12)
                                      ))
        elif type(layout) in (list, tuple) and len(layout) > 0:
            if isinstance(layout[0], Column):
                fs = layout
            elif isinstance(layout[0], (Fieldset, TabHolder)):
                fs = (Col('full', *layout, horizontal=True, span=12),)
            else:
                fs = (
                    Col('full', Fieldset("", *layout, css_class="unsort no_title"), horizontal=True, span=12),)

            layout = Layout(Container(*fs))

            if self.detail_show_all:
                rendered_fields = [i[1] for i in layout.get_field_names()]
                container = layout[0].fields
                other_fieldset = Fieldset(_(u'Other Fields'), *[
                                          f for f in self.form_obj.fields.keys() if f not in rendered_fields])

                if len(other_fieldset.fields):
                    if len(container) and isinstance(container[0], Column):
                        container[0].fields.append(other_fieldset)
                    else:
                        container.append(other_fieldset)

        return layout

    @filter_hook
    def get_model_form(self, **kwargs):
        """
        Returns a Form class for use in the admin add view. This is used by
        add_view and change_view.
        """
        if self.exclude is None:
            exclude = []
        else:
            exclude = list(self.exclude)
        if self.exclude is None and hasattr(self.form, '_meta') and self.form._meta.exclude:
            # Take the custom ModelForm's Meta.exclude into account only if the
            # ModelAdmin doesn't define its own.
            exclude.extend(self.form._meta.exclude)
        # if exclude is an empty list we pass None to be consistant with the
        # default on modelform_factory
        exclude = exclude or None
        defaults = {
            "form": self.form,
            "fields": self.fields and list(self.fields) or '__all__',
            "exclude": exclude,
        }
        defaults.update(kwargs)
        return modelform_factory(self.model, **defaults)

    @filter_hook
    def get_form_helper(self):
        helper = FormHelper()
        helper.form_tag = False
        helper.include_media = False
        layout = self.get_form_layout()
        replace_field_to_value(layout, self.get_field_result)
        helper.add_layout(layout)
        cls_str = str if six.PY3 else basestring
        helper.filter(cls_str, max_level=20).wrap(ShowField, admin_view=self)
        return helper

    @csrf_protect_m
    @filter_hook
    def get(self, request, *args, **kwargs):
        form = self.get_model_form()
        self.form_obj = form(instance=self.obj)
        helper = self.get_form_helper()
        if helper:
            self.form_obj.helper = helper

        return self.get_response()

    @filter_hook
    def get_context(self):
        new_context = {
            'title': _('%s Detail') % force_text(self.opts.verbose_name),
            'form': self.form_obj,

            'object': self.obj,

            'has_change_permission': self.has_change_permission(self.obj),
            'has_delete_permission': self.has_delete_permission(self.obj),

            'content_type_id': ContentType.objects.get_for_model(self.model).id,
        }

        context = super(DetailAdminView, self).get_context()
        context.update(new_context)
        return context

    @filter_hook
    def get_breadcrumb(self):
        bcs = super(DetailAdminView, self).get_breadcrumb()
        item = {'title': force_text(self.obj)}
        if self.has_view_permission():
            item['url'] = self.model_admin_url('detail', self.obj.pk)
        bcs.append(item)
        return bcs

    @filter_hook
    def get_media(self):
        return super(DetailAdminView, self).get_media() + self.form_obj.media + \
            self.vendor('xadmin.page.form.js', 'xadmin.form.css')

    @filter_hook
    def get_field_result(self, field_name):

SHDjango/apps/app01/templates/home/capter_handler.html
{% extends "base.html" %}


{% block content %}
<!--内容-->
<div class="container" style="margin-top:76px">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title"><span class="glyphicon glyphicon-list-alt"></span>{{art_capter.art.a_title}}  章节详情</h3>
                </div>
                <div class="panel-body">
                    <h1 class="text-center">{{ art_capter.title }}</h1>时间:<span>{{art_capter.create_time}}</span>
                    <br>
                    <span>{{art_capter.content}}</span>

                </div>




            </div>
        </div>

    </div>


</div>
<!--内容-->
{% endblock %}

SHDjango/apps/app01/templates/home/detail.html
{% extends "base.html" %}

{% block content %}
<!--内容-->
<div class="container" style="margin-top:76px">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title"><span class="glyphicon glyphicon-list-alt"></span>&nbsp;文章详情</h3>
                </div>
                <div class="panel-body">
                    <h1 class="text-center">{{ art.a_title }}</h1>


                    <div align="center">
                        <a style="font-size: 18px;">价格:<span style="color: green"> {{art.a_price}}</span>元</a>
                    </div>
                    <div class="span" align="right">
                        <a class="btn primary btn-success" type="button"
                                                       href="/app/cart/add?id={{art.id}}">加入购物车</a>

                        <a class="btn primary btn-danger" type="button"
                                                       href="/app/cart/order">我的订单</a>

                    </div>



                    <div class="col-md-3">
                         <img data-original="/static/{{art.a_img}}" style="width:262px;height:166px;"
                         class="img-responsive center-block lazy" alt="">
                    </div>
                    <div class="col-md-9">
                        {{ art.a_content | safe }}

                    </div>
{#                        <div  style="position: absolute;right: 20px;bottom: 30px;">#}
{#                            <a class="label label-success" style="display:inline-block;width:150px;">被浏览{{time_visit }}次</a>#}
{#                        </div>#}
                </div>

                <ul id="ArtsTab" class="nav nav-tabs" style="margin-top: 50px;">
                    <li class="active">
                        <a href="#catalog" data-toggle="tab" style="color: cadetblue;font-size: 20px;">小说章节</a>
                    </li>
                    <li>
                        <a href="#discuss" data-toggle="tab" style="color: cadetblue;font-size: 20px;">讨论区</a>
                    </li>
                </ul>
                <div id="ArtsTabContent" class="tab-content">
                    <div class="tab-pane fade in active" id="catalog">

                        <h3 align="center">{{ art.a_title }} 章节 </h3>
                        <ul class="list-group">
                            {% for capter in art_capters %}
                            <a class="list-group-item" href="/app/capter?id={{capter.id}}">{{capter.title}}</a>
                            {% endfor %}
                        </ul>

                    </div>
                    <div class="tab-pane fade" id="discuss">

                        <h3 align="center">{{ art.a_title }} 的讨论区 </h3>

                        <!--  评论区表单  -->
                        <form action="{% url 'comments:art_comment' art.pk %}" method="post" class="comment-form">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12">
                                    <label for="{{ form.name.id_for_label}}">名字：</label>
                                    {{ form.name }}
                                    {{ form.name.errors }}
                                </div>
                                <div class="col-md-12">
                                    <label for="{{form.title.id_for_label}}">标题：</label>
                                    {{ form.title }}
                                    {{ form.title.errors }}
                                </div>

                                <div class="col-md-12">
                                    <label for="{{ form.text.id_for_label }}">评论：</label>
                                    <br>
                                    {{ form.text }}
                                    {{ form.text.errors }}
                                    <br>
                                    <button type="submit" class="comment-btn btn-success">发表评论</button>
                                </div>
                            </div>    <!-- row -->
                        </form>
                        <!--  评论区表单  -->
                        <br>

                        <!-- 评论区展示-->
                        <div class="comment-list-pannel">
                            <h3>评论列表，共 <span>{{comment_count}}</span> 条评论</h3>
                            <hr>
                            <ul class="comment-list list-unstyled">
                                {% for comment in comment_list %}
                                <li class="comment-item">
                                    <span class="glyphicon glyphicon-user label label-primary">{{ comment.name }}</span>
                                    &nbsp;&nbsp;
                                    <time class="glyphicon glyphicon-time label  label-success">{{ comment.created_time }}</time>

                                    <br><br>
                                    <div class="text">
                                        {{ comment.text }}
                                    </div>
                                </li>
                                <hr>
                                {% empty %}
                                暂无评论

                                {% endfor %}
                            </ul>
                        </div>
                        <!--  评论区展示 -->


                    </div>
                </div>



            </div>
        </div>

    </div>
</div>
<!--内容-->
{% endblock %}

SHDjango/apps/app01/templates/home/index.html
{% extends "base.html" %}

{% block carousel %}

<div class="container" id="myCarousel" style="margin-top:80px">
		<!-- 轮播图容器 -->
		<div id="carousel-example-generic" class="carousel slide">
			<!-- 轮播图上的圆圈链接 -->
			<ol class="carousel-indicators radiou">
				<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
				<li data-target="#carousel-example-generic" data-slide-to="1"></li>
				<li data-target="#carousel-example-generic" data-slide-to="2"></li>
			</ol>
			<!-- 轮播图具体内容 -->
			<div class="carousel-inner">
				<div class="item active">
					<img src="/static/images/fengmian1.jpeg" style="background-size:cover; height: 300px; width:1200px">
					<!-- 图上文字 -->
					<div class="carousel-caption">
						<h4>美丽俏佳人</h4>
						<p>美丽俏佳人</p>
					</div>
				</div>
				<div class="item">
					<img src="/static/images/shanhaijing.jpeg" style="background-size:cover; height: 300px; width:1200px">
					<!-- 图上文字 -->
					<div class="carousel-caption">
						<h4>山海经</h4>
						<p>山海经 密码</p>
					</div>
				</div>
				<div class="item">
                    <img src="/static/images/hudie.jpeg" style="background-size:cover; height: 300px; width:1200px">
					<!-- 图上文字 -->
					<div class="carousel-caption">
						<h4>新鸳鸯蝴蝶梦</h4>
						<p>新鸳鸯蝴蝶梦 名著</p>
					</div>
				</div>
			</div>
			<!-- 轮播图上的向前一图切换链接 -->
			<a href="#carousel-example-generic" data-slide="prev" class="left carousel-control">
				<span class="glyphicon glyphicon-chevron-left"></span>
			</a>
			<!-- 轮播图上的向后一图切换链接 -->
			<a href="#carousel-example-generic" data-slide="next" class="right carousel-control">
				<span class="glyphicon glyphicon-chevron-right"></span>
			</a>
		</div>
	</div>

{% endblock %}





{% block content %}
<!--文章列表-->
<section id="artlist" style="margin-top:76px">
    <div class="container">
        <div class="row wow fadeIn" data-wow-delay="0.6s">
            <div class="col-md-12 table-responsive">
                <table class="table text-left table-bordered" id="arttags">
                    <tr>
                        <td style="width:10%;">文章标签</td>
                        <td style="width:90%;">
                             <a class="label label-info" id="curtag0" href="{{url}}?t=0"><span
                                    class="glyphicon glyphicon-th-list"></span>&nbsp;全部</a>
                            {% for tag in tags %}
                                <a class="label label-info" id="curtag{{tag.id}}" href="{{url}}?t={{tag.id}}"><span
                                    class="glyphicon glyphicon-tag"></span>&nbsp;{{tag.t_name}}</a>
{#                            &nbsp;#}
                            {% endfor %}
                        </td>
                    </tr>
                </table>
            </div>
            {% for v in  data %}
            <div class="col-md-3">
                <div class="artlist text-center">
                    <!--<img data-original="holder.js/262x166"
                             class="img-responsive lazy center-block" alt="">-->
                    <img data-original="/static/{{v.a_img}}" style="width:262px;height:166px;"
                         class="img-responsive center-block lazy" alt="">
                    <div class="text-left" style="margin-left:auto;margin-right:auto;width:210px;">
                        <span style="color:#999;font-style: italic;">{{v.a_title}}</span><br>
                        <p style="height: 80px;overflow:hidden;text-overflow: ellipsis;white-space: nowrap">{{v.a_info}}</p>

                    </div>
                    <a href="/app/detail?id={{v.id}}" class="btn btn-primary" target="_blank" role="button">
                        <span class="glyphicon glyphicon-eye-open"></span>&nbsp;阅读</a>
                </div>
            </div>
            {% endfor %}

            <div class="col-md-12 text-center" style="margin-top:12px;">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        <li>
                            <a href="{{url}}?page=1&t={{t}}" aria-label="First">
                                <span aria-hidden="true">首页</span>
                            </a>
                        </li>
                        <li>
                            <a href="{{url}}?page={{prev}}&t={{t}}"
                               aria-label="Previous">
                                <span aria-hidden="true">上一页</span>
                            </a>
                        </li>
                        {% for v in pagerange %}
                        {% if v == page %}
                        <li class="active"><a href="{{url}}?page={{ v }}&t={{t}}">{{v}}</a></li>
                        {% else %}
                        <li><a href="{{url}}?page={{ v }}&t={{t}}">{{ v }}</a></li>
                        {% endif %}
                        {% endfor %}
                        <li>
                            <a href="{{url}}?page={{next}}&t={{t}}"
                               aria-label="Next">
                                <span aria-hidden="true">下一页</span>
                            </a>
                        </li>
                        <li>
                            <a href="{{url}}?page={{pagenum}}&t={{t}}"
                               aria-label="Last">
                                <span aria-hidden="true">尾页</span>
                            </a>
                        </li>
                    </ul>
                </nav>
                <a class="label label-success" style="display:inline-block;width:150px;">共{{pagenum}}页</a>
                &nbsp;
                <a class="label label-info" style="display:inline-block;width:150px;">共{{total}}条记录</a>
{#                <a class="label label-success" style="display:inline-block;width:150px;">被浏览{{time_visit }}次</a>#}
            </div>
        </div>
    </div>

</section>
<!--电影列表-->
{% endblock %}

{% block js %}

<script>
    $(document).ready(function(){
        $("#curtag{{t}}").attr("class","label label-danger");
    });
</script>

{% endblock %}

SHDjango/apps/app01/templates/home/login_handler.html
{% extends 'base.html' %}

{% block css %}
    <link rel="stylesheet" href="/static/base/css/msg_style.css">
{% endblock %}

{% block content %}

    <!--内容-->
<div class="container" style="margin-top:76px">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title"><span class="glyphicon glyphicon-list-alt"></span>&nbsp;会员登录</h3>
                </div>
                <div class="panel-body">

                    <form action="{% url 'user_login' %}" method="post" class="smart-green">{% csrf_token %}

                        <h1>用户登录</h1>

{#                        {{ form.as_p }}#}
{##}
{#                        {% if messages %}#}
{#                           <ul>#}
{#                              {% for msg in messages %}#}
{#                                <li style="color: red">{{msg.message}}</li>#}
{#                               {% endfor %}#}
{#                           </ul>#}
{##}
{#                        {% endif %}#}
                        <label for="username">用户名</label>
                        {{ form.username }}
                        <span style="color: red">{{ form.username.errors }}</span>
                        <label for="password">密码</label>
                        {{ form.password }}
                        <span style="color: red">{{ form.password.errors }}</span>
{#                        <span style="color: red">#}
{#                            {% if form | all_errors %}#}
{#                                {{ form | all_errors }}#}
{#                            {% endif %}#}
{#                        </span>#}
                        <div class="form-group">
                            <label for="password">验证码</label>
                            <div class="row">
                                <div class="col-xs-7">
                                    <input type="text" class="form-control" name="check_code"
                                    id="check_code" placeholder="请输入验证码">
                                </div>
                                <div class="col-xs-5">
                                    <img id="check_code_img" src="/app/create_code_img/"
                                    onclick="refresh_check_code(this)">
                                </div>
                            </div>
                            <span style="color: red">{{ errors.check_code }}</span>
                        </div>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" value="1" name="auto_login">一个月内自动登录
                            </label>
                        </div>

                        <div class="success-msg"></div>
                        <label>
                            <span>&nbsp;</span>
                            <input type="submit" class="button" value="提交登录"/>
                        </label>

                        <label>
                            <span>忘记账号？请点击 <a href="/app/register/">注册</a></span>
                        </label>

                    </form>

                </div>
            </div>
        </div>

    </div>
</div>
<!--内容-->


{% endblock %}

{% block js %}
<script>
function refresh_check_code(ths) {
    ths.src += '?';
    {#                src后面加问好会自动刷新验证码img的src#}
}
</script>
{% endblock %}